[phases.setup]
nixPkgs = ["python311", "nodejs", "ffmpeg"]

[phases.install]
# Forzamos la instalaci√≥n de pip antes de instalar los requerimientos
cmds = [
    "python -m ensurepip",
    "python -m pip install --upgrade pip",
    "cd Backend && pip install -r requirements.txt"
]

[start]
cmd = "cd Backend && python api.py"