[phases.setup]
nixPkgs = ["python311", "nodejs", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Forzamos a que use la versión más reciente disponible de node en el entorno
cmds = ["node -v && cd Frontend && npm run build"]

[start]
cmd = "cd Backend && /app/.venv/bin/python api.py"