[phases.setup]
nixPkgs = ["python311", "nodejs_22", "ffmpeg"]

[phases.install]
cmds = [
    "node -v", # Esto imprimirá la versión en los logs para confirmar
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
cmds = ["cd Frontend && npm run build"]

[start]
cmd = "cd Backend && /app/.venv/bin/python api.py"