[phases.setup]
nixPkgs = ["python311", "nodejs", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "cd Backend && /app/.venv/bin/python api.py"