[phases.setup]
# Usamos nombres que Nix reconoce universalmente
nixPkgs = ["python311", "nodejs", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Compilaci√≥n de la interfaz de React
cmds = ["cd Frontend && npm run build"]

[start]
# Comando para que Railway sirva el Frontend
cmd = "cd Frontend && npm run preview -- --host 0.0.0.0 --port $PORT"