[phases.setup]
# Forzamos la instalación de los lenguajes necesarios
nixPkgs = ["python311", "nodejs_20", "ffmpeg"]

[phases.install]
# Ahora los comandos reconocerán 'python' y 'npm'
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Compilamos el Frontend de React
cmds = ["cd Frontend && npm run build"]

[start]
# Ejecutamos el servidor de Python
cmd = "cd Backend && /app/.venv/bin/python api.py"