[phases.setup]
# Usamos 'nodejs_20' (Node 20+) que cumple con los requisitos de Vite (20.19+ o 22.12+)
nixPkgs = ["python311", "nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
    "node -v",
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Compilación del frontend con la versión correcta de Node
cmds = ["cd Frontend && npm run build"]

[start]
# Ejecución del servidor backend
cmd = "cd Backend && /app/.venv/bin/python api.py"