# Usamos 'nodejs_22' explícitamente porque el default es v18 y Vite requiere v20+
nixPkgs = ["python311", "nodejs_22", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Forzamos la compilación del frontend de React
cmds = ["cd Frontend && npm run build"]

[start]
# Iniciamos el servidor de Python usando el entorno virtual creado
cmd = "cd Backend && /app/.venv/bin/python api.py"