[phases.setup]
# Cambiamos a nodejs_22 para superar el requisito de Vite 20.19+
nixPkgs = ["python311", "nodejs_22", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Compilación del frontend con la versión correcta de Node
cmds = ["cd Frontend && npm run build"]

[start]
# Ejecución del servidor backend
cmd = "cd Backend && /app/.venv/bin/python api.py"