[phases.setup]
# Esto garantiza que los binarios existan en el contenedor
nixPkgs = ["python311", "nodejs", "ffmpeg"]

[phases.install]
# Ahora 'python' ya será reconocido por el sistema
cmds = [
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install --upgrade pip",
    "cd Backend && /app/.venv/bin/pip install -r requirements.txt",
    "cd Frontend && npm install"
]

[phases.build]
# Compilación del frontend de React
cmds = ["cd Frontend && npm run build"]

[start]
# Ejecución del backend usando el entorno virtual
cmd = "cd Backend && /app/.venv/bin/python api.py"