[build]
# Configuraci√≥n global (opcional)

# Backend (Python)
[[services]]
name = "backend"
root = "./Backend"
start = "python api.py"
buildCommand = "pip install -r requirements.txt"

# Frontend (Node.js)
[[services]]
name = "frontend"
root = "./Frontend"
start = "npm start"
buildCommand = "npm install && npm run build"
